# Generated by Django 4.2 on 2023-05-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datalinker",
            name="avatar_url",
            field=models.CharField(
                default="https://img1.baidu.com/it/u=3957872274,3666965360&fm=253&fmt=auto&app=120&f=JPEG?w=855&h=659",
                max_length=1000,
            ),
        ),
        migrations.AddField(
            model_name="datalinker",
            name="self_introduction",
            field=models.CharField(default="这个人很懒，什么都没有留下", max_length=1000),
        ),
    ]
