# Generated by Django 4.2 on 2023-05-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("article_id", models.AutoField(primary_key=True, serialize=False)),
                ("author_name", models.CharField(max_length=100)),
                ("author_id", models.IntegerField()),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("create_time", models.DateTimeField(auto_now=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
